name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt','**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path -Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path -Path dev-requirements.txt) { pip install -r dev-requirements.txt }

      - name: Editable install package
        run: |
          python -m pip install -e ./src

      - name: Run tests
        # Note: this repository uses the local `ollama` binary (CLI) for model runs.
        # CI runs unit tests only and does not require a running Ollama HTTP API.
        # If you need integration tests that exercise the real model, add a
        # separate job that runs on a self-hosted runner with the `ollama`
        # binary installed or mock the HTTP endpoints in tests.
        run: |
          pytest -q
